# ----------------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator (autorest: 3.7.3, generator: @autorest/powershell@3.0.468)
# Changes may cause incorrect behavior and will be lost if the code is regenerated.
# ----------------------------------------------------------------------------------
Write-Host -ForegroundColor Green 'Packing module...'
dotnet pack $PSScriptRoot --no-build /nologo
Write-Host -ForegroundColor Green '-------------Done-------------'